# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mecab.proto for package 'mecabgrpc'

require 'grpc'
require 'mecab_pb'

module Mecabgrpc
  module MecabService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mecabgrpc.MecabService'

      rpc :parse, RequestString, stream(ResponseNode)
    end

    Stub = Service.rpc_stub_class
  end
end
