# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mecab.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mecab.proto", :syntax => :proto3) do
    add_message "mecabgrpc.ResponseNode" do
      optional :surface, :string, 1
      optional :feature, :string, 2
      optional :id, :uint32, 3
      optional :length, :uint32, 4
      optional :rlength, :uint32, 5
      optional :rcAttr, :uint32, 6
      optional :lcAttr, :uint32, 7
      optional :posid, :uint32, 8
      optional :char_type, :uint32, 9
      optional :stat, :uint32, 10
      optional :isbest, :uint32, 11
      optional :alpha, :float, 12
      optional :beta, :float, 13
      optional :prob, :float, 14
      optional :wcost, :int32, 15
      optional :cost, :int32, 16
    end
    add_message "mecabgrpc.RequestString" do
      optional :body, :string, 1
    end
  end
end

module Mecabgrpc
  ResponseNode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mecabgrpc.ResponseNode").msgclass
  RequestString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mecabgrpc.RequestString").msgclass
end
